export enum NotificationType {
  TASK_ASSIGNED = 'TASK_ASSIGNED',
  TASK_UPDATED = 'TASK_UPDATED',
  TASK_COMMENTED = 'TASK_COMMENTED',
  PROJECT_INVITED = 'PROJECT_INVITED',
  PERMISSION_CHANGED = 'PERMISSION_CHANGED',
  MENTION = 'MENTION',
}
