export enum WidgetType {
  TASK_LIST = 'TASK_LIST',
  KANBAN = 'KANBAN',
  TIMELINE = 'TIMELINE',
  FILES = 'FILES',
  AI_ASSISTANT = 'AI_ASSISTANT',
  DEPENDENCY_GRAPH = 'DEPENDENCY_GRAPH',
  ACTIVITY_FEED = 'ACTIVITY_FEED',
  ANALYTICS = 'ANALYTICS',
  CALENDAR = 'CALENDAR',
}
